@HostAddress = http://localhost:5002
@GAME_ID = 68aba81b502ee98cefd193a4
@GAME_LIBRARY_ID = 68ab8df2b86e6028f31939ca

###GAME ENDPOINTS###

GET {{HostAddress}}/API/Game/
Accept: application/json

###

GET {{HostAddress}}/API/Game/{{GAME_ID}}
Accept: application/json

###

POST {{HostAddress}}/API/Game
Accept: application/json
Content-Type: application/json

{
  "name": "Novo jogo 3",
  "description": "Descrição do novo jogo 3",
  "price": 50,
  "releasedDate": "2025-08-24",
  "tags": [
    "estrategia", "acao", "tiro em primeira pessoa"
  ]
}

###
PUT {{HostAddress}}/API/Game/{{GAME_ID}}
Accept: application/json
Content-Type: application/json

{
    "description": "Descrição atualizada via arquivo"
}

###
PATCH {{HostAddress}}/API/Game/Tags/{{GAME_ID}}
Accept: application/json
Content-Type: application/json

{
  "tags": [
    "rpg",
    "estrategia em turnos"
  ]
}

###
DELETE {{HostAddress}}/API/Game/{{GAME_ID}}
Accept: application/json

###GAME LIBRARY ENDPOINTS###

GET {{HostAddress}}/API/GameLibrary/{{GAME_LIBRARY_ID}}
Accept: application/json

###

GET {{HostAddress}}/API/GameLibrary/User/usuarioBiblioteca
Accept: application/json

###

POST {{HostAddress}}/API/GameLibrary
Accept: application/json
Content-Type: application/json

{
  "userId": "usuarioBiblioteca",
  "games": [{
    "id": "{{GAME_ID}}",
    "name": "teste2",
    "tags": [
      "rpg",
      "estrategia em turnos"
    ]
  }]
}

###

POST {{HostAddress}}/API/GameLibrary/{{GAME_LIBRARY_ID}}/addGame
Accept: application/json
Content-Type: application/json

{
  "id": "{{GAME_ID}}",
  "name": "teste2",
  "tags": [
    "rpg",
    "estrategia em turnos"
  ]
}

###

DELETE {{HostAddress}}/API/GameLibrary/{{GAME_LIBRARY_ID}}/removeGame
Accept: application/json
Content-Type: application/json

{
  "id": "{{GAME_ID}}"
}